services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
      - PASSWORD=${ROOT_PASSWORD}
    volumes:
      - ./config:/config
      - ${ROOT_PROGRAMS}:/workspace
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
