services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/srv
      - FB_ADDRESS=0.0.0.0
    volumes:
      - ${ROOT_VOLUME}/filebrowser_data/filebrowser_files:/srv
      - ${ROOT_VOLUME}/filebrowser_data/filebrowser.db:/database/filebrowser.db
      - ${ROOT_VOLUME}/filebrowser_data/settings.json:/config/settings.json
    user: "1002:1002"
    networks:
      - proxy

networks:
  proxy:
    external: true