services:
  watchtower:
    image: containrrr/watchtower
    platform: linux/arm64
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.53
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - TZ=Europe/Paris
    networks:
      - proxy

networks:
  proxy:
    external: true
