services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${ROOT_VOLUME}/uptime-kuma_data:/app/data
    restart: always
    networks:
      - proxy
    dns:
      - ${DNS}
      
networks:
  proxy:
    external: true