services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ${ROOT_CONFIG}:/app/config
    restart: unless-stopped
    environment:
      - YOUR_BASE_DOMAIN=${DOMAIN}
    networks:
      - proxy
    dns:
      - ${DNS}

networks:
  proxy:
    external: true
